# Generated by Django 3.1.6 on 2021-08-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Soru', 'verbose_name_plural': 'Sorular'},
        ),
        migrations.AlterModelTable(
            name='question',
            table='Soru',
        ),
    ]
