# Generated by Django 3.1.6 on 2021-08-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210829_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Soru', 'verbose_name_plural': 'Soru'},
        ),
    ]
