# Generated by Django 3.1.6 on 2021-08-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210829_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Soru', 'verbose_name_plural': 'Sorular'},
        ),
        migrations.AlterField(
            model_name='question',
            name='html',
            field=models.TextField(verbose_name='Soru'),
        ),
    ]
