# Generated by Django 3.1.6 on 2021-08-21 20:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinifmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='isim', unique=True),
        ),
    ]
