# Generated by Django 3.1.6 on 2021-08-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazilarmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilarmodel',
            name='konular',
            field=models.ManyToManyField(related_name='yazi_konu', to='blog.KonuModel'),
        ),
    ]
