# Generated by Django 3.1.6 on 2021-02-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_yorummodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='olusturma_tarihi',
            new_name='olusturulma_tarihi',
        ),
    ]
