from .iletisim import iletisim
from .anasayfa import anasayfa
from .kategori import KategoriListView
from .yazilarim import yazilarim
from .detay import DetayView
from .yorum_sil import yorum_sil
from .yazi_sil import YaziSilDeleteView
from .yazi_guncelle import yazi_guncelle
from .yazi_ekle import YaziEkleCreateView
from .onemli_siteler import onemli_siteler