from .iletisim import IletisimFormView
from .anasayfa import anasayfa
from .yazilarim import yazilarim
from .detay import DetayView
from .yorum_sil import yorum_sil
from .yazi_sil import YaziSilDeleteView
from .yazi_guncelle import YaziGuncelleUpdateView
from .yazi_ekle import YaziEkleCreateView
from .onemli_siteler import onemli_siteler
from .sinif import SinifListView
from .konu import KonuListView